### ISSUE TITLE
运行时报个错

### ISSUE THREAD

**Issue by majiang26** [leon-fong/health-helper#4]
![Uploading 微信图片_20240308124320.png…]()

**Comment by leon-fong** [comment]
请提供具体报错信息

**Comment by majiang26** [comment]
D:\idea_workspace\health-helper\node_modules\@tarojs\plugin-platform-weapp\node_modules\@tarojs\service\dist\platform-plugin-base\mini.js:21
        this.platformType = shared_1.PLATFORM_TYPE.MINI;
                                                   ^
TypeError: Cannot read properties of undefined (reading 'MINI')

**Comment by majiang26** [comment]
启动  开发者工具-项目目录  D:\idea_workspace\health-helper\dist
D:\idea_workspace\health-helper\node_modules\.pnpm\vue-loader@16.8.3_@vue+compiler-sfc@3.2.31_vue@3.2.31_webpack@5.90.3\node_modules\vue-loader\dist\pluginWebpack5.js:44
        const normalModule = compiler.webpack.NormalModule || NormalModule;
                                              ^

TypeError: Cannot read properties of undefined (reading 'NormalModule')

用pnpm安装后，启动时报的

**Comment by majiang26** [comment]
启动  开发者工具-项目目录  D:\idea_workspace\health-helper\dist
D:\idea_workspace\health-helper\node_modules\.pnpm\vue-loader@16.8.3_@vue+compiler-sfc@3.2.31_vue@3.2.31_webpack@5.90.3\node_modules\vue-loader\dist\pluginWebpack5.js:44
        const normalModule = compiler.webpack.NormalModule || NormalModule;
                                              ^
TypeError: Cannot read properties of undefined (reading 'NormalModule')
用pnpm安装后，启动时报的

**Comment by gongzhuoqun** [comment]
遇到一样的错误
